name: CI

on:
  push:
    paths:
      - .github/workflows/ci.yml
      - "**/*.tf"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@fc711fa910b93cba0f3fbecaafc9f42fd0c411cb # v2.0.0
        with:
          tofu_wrapper: false

      - name: Check HCL formatting
        run: tofu fmt -check -recursive -diff
