name: CI

on:
  push:
    paths:
      - .github/workflows/ci.yml
      - "**/*.tf"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@a1320f892987e89d278cc92dc5adc984fb93aca4 # v2.0.2
        with:
          tofu_wrapper: false

      - name: Check HCL formatting
        run: tofu fmt -check -recursive -diff
