name: CI

on:
  push:
    paths:
      - "**/*.tf"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v2
        with:
          tofu_wrapper: false

      - name: Check HCL formatting
        run: tofu fmt -check -recursive -diff
