name: Terraform Plan

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: '22'

      - name: Install dependencies
        run: pnpm install

      - name: Setup Terraform for generate providers
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.11.3'

      - name: Generate providers
        env:
          MACKEREL_API_KEY: stub
        run: pnpm cdktf provider get

      - name: Plan AWS
        uses: hashicorp/terraform-cdk-action@v8
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          mode: plan-only
          stackName: aws
          terraformCloudToken: ${{ secrets.TF_API_TOKEN }}
          terraformVersion: '1.11.3'

      - name: Plan Cloudflare
        uses: hashicorp/terraform-cdk-action@v8
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          mode: plan-only
          stackName: cloudflare
          terraformCloudToken: ${{ secrets.TF_API_TOKEN }}
          terraformVersion: '1.11.3'

      - name: Plan Mackerel
        uses: hashicorp/terraform-cdk-action@v8
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          mode: plan-only
          stackName: mackerel
          terraformCloudToken: ${{ secrets.TF_API_TOKEN }}
          terraformVersion: '1.11.3'

      - name: Plan Terraform Cloud
        uses: hashicorp/terraform-cdk-action@v8
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          mode: plan-only
          stackName: terraform-cloud
          terraformCloudToken: ${{ secrets.TF_API_TOKEN }}
          terraformVersion: '1.11.3'
