name: Terraform Plan

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: 20

      - name: Install dependencies
        run: pnpm install

      - name: build ikapri
        run: |
          pwd
          ls
          pnpm install
          pnpm run build
        working-directory: ./src/assets/workers/ikapri

      - name: build kuroneko-tracker-feed
        run: |
          pwd
          ls
          pnpm install
          pnpm run build
        working-directory: ./src/assets/workers/kuroneko-tracker-feed

      - name: Plan
        uses: hashicorp/terraform-cdk-action@v0.1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          mode: plan-only
          stackName: cloudflare
          terraformCloudToken: ${{ secrets.TF_API_TOKEN }}
