name: Terraform Plan

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Plan
        uses: hashicorp/terraform-cdk-action@v0.1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          mode: plan-only
          terraformCloudToken: ${{ secrets.TF_API_TOKEN }}
